name: 'Sync YuQue'
author: 'Liu Bowen'
description: 'Sync post data from YuQue webhook'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands.
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  out-dir:
    description: "Where should our documentations be place in",
    default: 'docs'
  out-file:
    description: 'As generated markdown file name'
    required: true
  content:
    description: 'As generated markdown file content',
    required: true
runs:
  using: 'node15'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
